development:
  adapter: postgresql
  database: ukitchen_development
  username: rails_dev
  password: asdf
  encoding: unicode
  host: localhost
  pool: 5
test:
  adapter: postgresql
  database: ukitchen_test
  username: rails_dev
  password: asdf
  encoding: unicode
  host: localhost
  pool: 5
